spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: @google.client-id@
            client-secret: @google.client-secret@
          facebook:
            client-id: @facebook.client-id@
            client-secret: @facebook.client-secret@
          linkedin:
            client-id: @linkedin.client-id@
            client-secret: @linkedin.client-secret@
            provider: linkedin
            scope: r_basicprofile,r_emailaddress
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Linkedin





        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            #user-info-uri: https://api.linkedin.com/v1/people/~?format=json
            user-info-uri: https://api.linkedin.com/v1/people/~:(id,email-address,first-name,last-name,picture-url)?format=json
            user-name-attribute: id







